export {default as HomeLayout} from "./HomeLayout"
export {default as Error} from "./Error"
export {default as Login} from "./Login"
export {default as Calender} from "./Calender"
export {default as Dashboard} from "./Dashboard"
export {default as ImportXML} from "./ImportXML"
export {default as Register} from "./Register"
export {default as Blog} from "./Blog"
export {default as Bookings} from "./Bookings"
export{default as Profile} from "./Profile"
export{default as CreateBooking} from "./CreateBooking"
export{default as SingleBlogPage} from "./SingleBlogPage"

